[build]
  command = "rm -rf node_modules .next && npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"

# Plugin Next.js oficial para Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Runtime Node.js para todas as functions
  node_bundler = "esbuild"
  
[dev]
  framework = "next"
  targetPort = 3000
  
# Configurações de ambiente para garantir variáveis acessíveis
[context.production.environment]
  NODE_ENV = "production"
  
[context.deploy-preview.environment]
  NODE_ENV = "development"